apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gitops-policy-all-clusters
policyDefaults:
  namespace: acm-policies
  complianceType: musthave
  remediationAction: enforce 
  severity: medium
  placement:
    placementRuleName: all-clusters-placement-rule
policies:
  - name: gitops-policy-all-clusters
    manifests:
      - path: all-clusters
